// TEAM
export const SET_SELECTED_TEAM = "SET_SELECTED_TEAM";
export const FETCH_TEAMS = "FETCH_TEAMS";

// WORKERS
export const FETCH_WORKERS = "FETCH_WORKERS";
export const FETCH_WORKERS_BY_TEAM = "FETCH_WORKERS_BY_TEAM";
export const FETCH_WORKER = "FETCH_WORKER";

// WORK POSITION
export const FETCH_WORK_POSITIONS = "FETCH_WORK_POSITIONS";

// COMPANIES
export const FETCH_COMPANIES = "FETCH_COMPANIES";

// JOURNEY
export const SET_JOURNEY_CREATE_DATE = "SET_JOURNEY_CREATE_DATE";
