// TEAM
export const SET_SELECTED_TEAM = "SET_SELECTED_TEAM";
export const FETCH_TEAMS = "FETCH_TEAMS";
export const SAVE_TEAMS_TO_STORE = "SAVE_TEAMS_TO_STORE";

// WORKERS
export const FETCH_WORKERS = "FETCH_WORKERS";
export const FETCH_WORKERS_BY_TEAM = "FETCH_WORKERS_BY_TEAM";
export const FETCH_WORKER = "FETCH_WORKER";
export const UPDATE_REPLACED_WORKERS = "UPDATE_REPLACED_WORKERS";
export const SET_SUBSTITUTE_INFO = "SET_SUBSTITUTE_INFO";
export const SET_WORKER_REPORTED_INFO = "SET_WORKER_REPORTED_INFO";
export const ADD_WORKER_TO_TEAM = "ADD_WORKER_TO_TEAM";
export const RESET_WORKERS = "RESET_WORKERS";

// WORK POSITION
export const FETCH_WORK_POSITIONS = "FETCH_WORK_POSITIONS";

// COMPANIES
export const FETCH_COMPANIES = "FETCH_COMPANIES";

// JOURNEY
export const SET_JOURNEY_CREATE_DATE = "SET_JOURNEY_CREATE_DATE";
export const OPENED_JOURNEYS = "OPENED_JOURNEYS";

// VEHICLE
export const UPDATE_REPLACED_VEHICLE = "UPDATE_REPLACED_VEHICLE";
export const SET_TEAM_VEHICLE = "SET_TEAM_VEHICLE";
